# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c14b726ffd269c7bd5250a09857d18b96075d9618caec9378a2d62f0af9a04accd2828eed108bf736bd28efee011860216e08ab0cee76625dd7b0be762d5ada

test:
  secret_key_base: b45c1b99b716de2677dda5ccd383dd8d8d03937ca43e1c5acd46960b3200d5af12e9fc03a075ddb4194455394b81725b6acf8fa19a1faaa2260cee633c7aacd2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
